# Workflow 이름
name: Integration with Gradle

#브랜치 지정
on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # Repository Checkout
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    # Java Setting
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
    # gradlew 권한 부여
    - name: Grant gradlew
      run: chmod +x gradlew
    # WAS Gradle 빌드
    - name: Build with Gradle
      run: ./gradlew build -x test
    # 도커 이미지 빌드
    - name: Docker Build Image
      run: docker build -t commerce-was .
    # docker-compose excute
    - name: execute docker-compose
      run: docker-compose up -d
